version : "3"

services :
  kopring :
    container_name : kopring
    build :
      context :    .
      dockerfile : Dockerfile
    networks :
      - kopring_net
    ports :
      - 8080:8080
    environment :
      SPRING_DATASOURCE_URL :      jdbc:mysql://localhost:33306/kopringdb?useSSL=false&serverTimezone=UTC&autoReconnection=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : root
      SPRING_REDIS_HOST :          localhost
      SPRING_REDIS_PORT :          36379
    volumes :
      - C:/Users/alban/Documents/app_logs/spring.log:/app/logs/kopring.log
    depends_on :
      - mysql
      - redis
  mysql :
    container_name : mysql
    networks :
      - kopring_net
    image :          mysql
    ports :
      - 33306:3306
    environment :
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kopringdb
  redis :
    container_name : redis
    networks :
      - kopring_net
    image :          redis
    ports :
      - 36379:6379

networks :
  kopring_net :
    driver : bridge