spring :
  datasource :
    #    url :               jdbc:mariadb://mysql:33306/kopringdb?useSSL=false&allowPublicKeyRetrieval=true
    url :               jdbc:h2:mem:test
    username :          root
    password :          root
    driver-class-name : org.h2.Driver
  redis :
    host : redis
    port : 36379

  jpa :
    generate-ddl : true
    hibernate :
      ddl-auto :   'create-drop'
      format_sql : true
  h2 :
    console :
      enabled : true
      path :    /h2



jwt :
  header :
    access :  my-jwt-access
    refresh : my-jwt-refresh

server :
  port : 8080
  servlet :
    context-path : /

#logging :
#  file :
#    name : kopring.log
#    path : /app/logs

