spring :
  datasource :
    url :               jdbc:mariadb://mysql:33306/kopringdb?useSSL=false&allowPublicKeyRetrieval=true
    username :          root
    password :          root
    driver-class-name : org.mariadb.jdbc.Driver

  redis :
    host : redis
    port : 36379

  jpa :
    generate-ddl : true
    #    show-sql :                        true
    properties :
      hibernate :
        ddl-auto : validate
#    defer-datasource-initialization : true
#    database :                        mysql

#  sql :
#    init :
#      mode : always
jwt :
  header :
    access :  my-jwt-access
    refresh : my-jwt-refresh

server :
  port : 8080
  servlet :
    context-path : /

logging :
  file :
    name : kopring.log
    path : /app/logs

