server :
  port : 8080
  servlet :
    context-path : /

spring :
  datasource :
    url :               jdbc:h2:mem:test
    username :          root
    password :          root
    driver-class-name : org.h2.Driver
