server :
  port : 8080
  servlet :
    context-path : /

spring :
  datasource :
    url :               jdbc:mysql://kopring-mysql:3306/kopringdb
    username :          root
    password :          root
    driver-class-name : com.mysql.cj.jdbc.Driver

  redis :
    host : redis-host.default.svc.cluster.local
    port : 6379

  jpa :
    generate-ddl :                    true
    show-sql :                        true
    hibernate :
      ddl-auto : create-drop
    defer-datasource-initialization : true

  sql:
    init :
      mode : always

jwt :
  header :
    access :  my-jwt-access
    refresh : my-jwt-refresh